### ISSUE TITLE
"modern dark" feedback

### ISSUE THREAD

**Issue by adrianinsaval** [MisterMakerNL/Freecad-Built-in-themes-beta#1]
this is confusing to me:
![image](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/36372335/1eda84d8-5025-4dcb-973d-76eee8620890)

normally I would expect the lighter color to be the "selected" tab, instead it's the other way around and the current tab is the one that's indistinguishable from the background and the one that looks highlighted is the one that is inactive. Same situation with the combo view tabs.

Is the blue line in this slider intended? (using pink variant)
![image](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/36372335/419a1fc1-bb47-455d-bb06-3b3b219d94af)

the unticked checkboxes are not distinguishable in this preference page:
![image](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/36372335/af152041-511d-4b83-9de6-8bdaa7a1de50)

is the lack of frames in this page intended? looks odd to me:
![image](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/36372335/79e8f615-b23a-4412-9234-7775ca1d0645)
I mean the python example and the display item list

text in cells with an alias are unreadable in spreadsheet WB:
![image](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/36372335/12c14e93-c841-4ff7-8042-32efa00c5878)
but this might just be because I couldn't install the preference pack and I'm only using the stylesheet.

commands that have a dropdown don't have anything indicating they do
![image](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/36372335/39b5566c-adfa-4fc1-86f5-a990c3ab26ec)
and separators are invisible but this might be by choice? also the icons look too densely packed but this might again be by choice.

**Comment by MisterMakerNL** [comment]
Ah I see I am missed uploading some icons, bit of a puzzle as I don't want to upload already available icons.
The design intent of the tabs was that the non0active tabs look like buttons and also function as buttons to switch to that tab.
I do see that firefox also has the active tab bright and the rest dark, so I will probably test your suggestion and see how it looks.
The missing frames is not always intended, but I do try to remove as much clutter as possible. And sometimes there are way to many frames.
btw nice feedback I can work with that!!

**Comment by adrianinsaval** [comment]
> Ah I see I am missed uploading some icons, bit of a puzzle as I don't want to upload already available icons.

oh I didn't know there's icons that had to be copied! I just copied the stylesheet file alone because the preference pack was failing to install.

**Comment by MisterMakerNL** [comment]
Would this look better @adrianinsaval 
![afbeelding](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/29804962/bd2e22c7-aa67-4511-af0f-7b507c06396e)
This looks maybe better although I cannot get rid of the line next to the active tab.
![afbeelding](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/29804962/a2b7dffb-da38-41d7-bd7e-7278a0f099fc)

**Comment by adrianinsaval** [comment]
first looks better to me

**Comment by MisterMakerNL** [comment]
Fixed the slider made it nice and round and removed the wrong color from the border. Now I only have to do this 20 more times :)
![afbeelding](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/29804962/7dd60565-775e-4fad-8700-32094c550990)
Tabbar now looks like this:
![afbeelding](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/29804962/81fca1ed-6f59-48c3-9b22-ee63cd10224e)
![afbeelding](https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/assets/29804962/b6626c27-4de7-453b-bd76-d1c6edb11cbc)
