### ISSUE TITLE
Please add Prerequisites section to README

### ISSUE THREAD

**Issue by luzpaz** [MisterMakerNL/Freecad-Built-in-themes-beta#2]
What's the minimum version of FC that can run these themes? 

BTW, thank you for all your diligent work on this!

**Comment by MisterMakerNL** [comment]
I changed the cfg so that gradient gets set to 1 and radial, since Radial gets set to 1 last it will use radial if radial is available, if not it stays on gradient. So this way it should work on probably every version.

**Comment by MisterMakerNL** [comment]
Tested it on 0.20 seems to work fine now. Although radial background is sooo nice tho :)
I do see that I by accident deleted the link color in the cfg file.
There was a thread about non-themable stuff but can't find it do you have a link @luzpaz ?

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/issues/6805

**Comment by luzpaz** [comment]
What's left to do here?
