### ISSUE TITLE
Missed SVG icons

### ISSUE THREAD

**Issue by u2fly** [MisterMakerNL/Freecad-Built-in-themes-beta#5]
I just missed SVG files which are mentioned in QSS files, for example:

- https://github.com/MisterMakerNL/Freecad-Built-in-themes-beta/blob/main/Dark%20theme%20beta/Dark-blue_beta.qss

There are no next files:

- `images_dark-light/Hmovetoolbar_light.svg`
- `images_dark-light/Vmovetoolbar_light.svg`.
- `images_dark-light/branch_vline_light.svg`
- `images_dark-light/branch_more_light.svg`
- `images_dark-light/branch_end_open_light.svg`
- `images_dark-light/branch_end_closed_light.svg` 
- `images_dark-light/branch_end_light.svg`
- `images_dark-light/down_arrow_lighter.svg`
- `images_dark-light/down_arrow_disabled_light.svg`
- `images_dark-light/transparent.svg`
- `images_dark-light/splitter_vertical_dark.svg`
- `images_dark-light/splitter_vertical_light.svg` 
- `images_dark-light/splitter_horizontal_dark.svg`
- `images_dark-light/splitter_horizontal_light.svg`
- `images_dark-light/background_freecad_dark.svg`
- `images_dark-light/radiobutton_light.svg`

It might be either full list.

**Comment by MisterMakerNL** [comment]
Those are included in Freecad :)
